require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoffeeBeansController do

  # This should return the minimal set of attributes required to create a valid
  # CoffeeBean. As you add validations to CoffeeBean, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoffeeBeansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all coffee_beans as @coffee_beans" do
      coffee_bean = CoffeeBean.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coffee_beans).should eq([coffee_bean])
    end
  end

  describe "GET show" do
    it "assigns the requested coffee_bean as @coffee_bean" do
      coffee_bean = CoffeeBean.create! valid_attributes
      get :show, {:id => coffee_bean.to_param}, valid_session
      assigns(:coffee_bean).should eq(coffee_bean)
    end
  end

  describe "GET new" do
    it "assigns a new coffee_bean as @coffee_bean" do
      get :new, {}, valid_session
      assigns(:coffee_bean).should be_a_new(CoffeeBean)
    end
  end

  describe "GET edit" do
    it "assigns the requested coffee_bean as @coffee_bean" do
      coffee_bean = CoffeeBean.create! valid_attributes
      get :edit, {:id => coffee_bean.to_param}, valid_session
      assigns(:coffee_bean).should eq(coffee_bean)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoffeeBean" do
        expect {
          post :create, {:coffee_bean => valid_attributes}, valid_session
        }.to change(CoffeeBean, :count).by(1)
      end

      it "assigns a newly created coffee_bean as @coffee_bean" do
        post :create, {:coffee_bean => valid_attributes}, valid_session
        assigns(:coffee_bean).should be_a(CoffeeBean)
        assigns(:coffee_bean).should be_persisted
      end

      it "redirects to the created coffee_bean" do
        post :create, {:coffee_bean => valid_attributes}, valid_session
        response.should redirect_to(CoffeeBean.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coffee_bean as @coffee_bean" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeBean.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_bean => { "name" => "invalid value" }}, valid_session
        assigns(:coffee_bean).should be_a_new(CoffeeBean)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeBean.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_bean => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coffee_bean" do
        coffee_bean = CoffeeBean.create! valid_attributes
        # Assuming there are no other coffee_beans in the database, this
        # specifies that the CoffeeBean created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoffeeBean.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => coffee_bean.to_param, :coffee_bean => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested coffee_bean as @coffee_bean" do
        coffee_bean = CoffeeBean.create! valid_attributes
        put :update, {:id => coffee_bean.to_param, :coffee_bean => valid_attributes}, valid_session
        assigns(:coffee_bean).should eq(coffee_bean)
      end

      it "redirects to the coffee_bean" do
        coffee_bean = CoffeeBean.create! valid_attributes
        put :update, {:id => coffee_bean.to_param, :coffee_bean => valid_attributes}, valid_session
        response.should redirect_to(coffee_bean)
      end
    end

    describe "with invalid params" do
      it "assigns the coffee_bean as @coffee_bean" do
        coffee_bean = CoffeeBean.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeBean.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_bean.to_param, :coffee_bean => { "name" => "invalid value" }}, valid_session
        assigns(:coffee_bean).should eq(coffee_bean)
      end

      it "re-renders the 'edit' template" do
        coffee_bean = CoffeeBean.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeBean.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_bean.to_param, :coffee_bean => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coffee_bean" do
      coffee_bean = CoffeeBean.create! valid_attributes
      expect {
        delete :destroy, {:id => coffee_bean.to_param}, valid_session
      }.to change(CoffeeBean, :count).by(-1)
    end

    it "redirects to the coffee_beans list" do
      coffee_bean = CoffeeBean.create! valid_attributes
      delete :destroy, {:id => coffee_bean.to_param}, valid_session
      response.should redirect_to(coffee_beans_url)
    end
  end

end
